# Site settings
title: Catriona Munro
email: catriona.munro[@]college-de-france.fr
description: > # this means to ignore newlines until "baseurl:"
  Catriona Munro. Postdoc at Collège de France.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "catrionamunro.science" # the base hostname & protocol for your site
twitter_username: CatMunro_
github_username:  cmunro

# Build settings
markdown: kramdown
