# Site settings
title: Catriona Munro
email: catriona_munro[@]brown.edu
description: > # this means to ignore newlines until "baseurl:"
  Catriona Munro. PhD Student at Brown University
baseurl: "https://cmunro.github.io/" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: CatMunro_
github_username:  cmunro

# Build settings
markdown: kramdown
